<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FlightListTable</name>
   <tag></tag>
   <elementGuidId>e338152d-cc67-4f3a-94f5-1a4413db9c00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>table</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
